In [ ]:
import pandas
import numpy

l1 = "label_1"
l2 = "label_2"
l3 = "label_3"
l4 = "label_4"

labels = [l1,l2,l3,l4]
age_label = l2
features = [f'feature_{i}' for i in range(1,257)]

In [ ]:
train_df = pandas.read_csv('train.csv')
train_df.head()


feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.928826  -0.291540   1.105909   2.070652   0.657838  -0.670940   
1  -1.709277  -1.008998   0.956611   4.313823  -0.669455   1.928765   
2  -1.906183  -0.357562  -0.682627   4.651838  -0.884940   1.159512   
3   0.697872  -2.218567  -0.572214   1.192062   0.329554   0.741364   
4  -1.976895  -0.496308   0.368102   3.739787  -0.132058   1.234980   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -0.968238   0.049916   1.111149   -1.834592  ...    -0.691538    -1.152522   
1   0.162550   0.152173   2.356505   -2.898549  ...    -0.668235    -0.532695   
2   1.354481  -1.432248   2.160144   -3.175735  ...    -0.026728     0.440408   
3   0.962354   0.993512   2.896854   -1.600380  ...     0.709032     0.812106   
4  -0.501003   0.881554   1.630941   -3.853953  ...    -0.599700    -1.024829   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.441157    -1.494434    -0.344974    -0.395641       45      NaN   
1     0.151163    -1.876885     1.651534    -2.706490       45      NaN   
2     2.745906    -0.680754    -0.643588    -2.587203       45      NaN   
3     1.055266    -0.915258    -0.924856    -1.318964       45      NaN   
4     1.869753    -2.498570     3.268253    -1.356606       45      NaN   

   label_3  label_4  
0        1        6  
1        1        6  
2        1        6  
3        1        6  
4        1        6  

[5 rows x 260 columns]

In [ ]:
valid_df = pandas.read_csv('valid.csv')
valid_df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.153148  -1.038098   1.419872   2.734152   1.154604  -1.086937   
1  -1.377524  -1.018393   1.102352   2.849025   0.440302  -1.149039   
2   0.889574  -2.743300  -0.320194   3.047766  -0.923335   1.741686   
3  -1.527213  -1.133121   0.385927   3.129767   0.229020   1.373105   
4   0.948176  -0.750248   0.008329   1.675338   1.941155  -0.783623   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -0.516225  -1.370325   2.865359   -1.879877  ...    -0.719046    -1.248530   
1  -0.789796  -2.258196   1.264268   -2.123730  ...    -1.383339    -0.787736   
2  -0.615148   0.756482   2.074775   -1.433126  ...     1.178322     0.035333   
3   0.919284  -0.755558   1.086973   -2.440614  ...    -0.664176     0.805059   
4  -0.485584  -0.261882   2.875204   -1.473030  ...    -0.665200    -0.428060   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.144460    -3.240056     0.052614     0.083108       45      NaN   
1     1.044895    -2.289637     0.199752    -0.712154       45      NaN   
2     0.857712    -1.928684     0.639870    -0.268576       45      NaN   
3     0.975368    -2.700269     1.523236    -1.259052       45      NaN   
4    -0.393100    -1.854657     2.207063    -0.342725       45      NaN   

   label_3  label_4  
0        1        6  
1        1        6  
2        1        6  
3        1        6  
4        1        6  

[5 rows x 260 columns]

In [ ]:
test_df = pandas.read_csv('test.csv')
test_df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.141206  -0.279703   1.019681   2.605902   0.460391  -1.167380   
1  -1.796767  -0.056758   0.771219   4.414086  -1.229059   1.732098   
2  -1.388968  -0.418296   0.186543   2.803852  -1.499095   1.395180   
3   1.276844  -0.112323  -0.310796   2.251175   0.283670  -0.581020   
4  -1.560815  -0.168494   1.249770   1.869219  -1.646049   0.132156   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -1.149165  -1.205164   2.468966   -2.729526  ...    -0.868282    -0.429783   
1   0.063241  -0.126311   1.322355   -3.461282  ...     0.227806     0.209200   
2   0.739648   0.274060   1.228789   -3.081147  ...    -0.692679     0.449235   
3  -0.024439  -0.306097   2.424685   -1.714863  ...    -0.690499    -1.077949   
4  -0.664602   0.483327   1.728020   -2.258071  ...    -0.510597     1.213396   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.438561    -1.625122     0.599944    -0.615575      NaN      NaN   
1     2.200402    -1.701029     1.163999    -1.570136      NaN      NaN   
2     1.377531    -1.854203    -0.040538    -2.164104      NaN      NaN   
3     0.930102    -2.758352    -0.246738    -1.389013      NaN      NaN   
4     2.497490    -1.597984    -0.163483    -1.735939      NaN      NaN   

   label_3  label_4  
0      NaN      NaN  
1      NaN      NaN  
2      NaN      NaN  
3      NaN      NaN  
4      NaN      NaN  

[5 rows x 260 columns]

In [ ]:
train_df['label_4'].value_counts()

6     19938
2      1449
0       955
12      954
7       938
13      482
1       481
11      480
10      480
3       479
5       478
9       472
4       469
8       465
Name: label_4, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler, RobustScaler

x_td = {}
x_vd = {}
y_td = {}
y_vd = {}
x_test = {}
y_test = {}

for target_label in labels:
  train_dataset = train_df[train_df['label_2'].notna()] if target_label == l2 else train_df
  valid_dataset = valid_df
  test_dataset = test_df

  scaler = RobustScaler()
  x_td[target_label] = pandas.DataFrame(scaler.fit_transform(train_dataset.drop(labels, axis=1)))
  y_td[target_label] = train_dataset[target_label]
  x_vd[target_label] = pandas.DataFrame(scaler.transform(valid_dataset.drop(labels, axis=1)))
  y_vd[target_label] = valid_dataset[target_label]
  x_test[target_label] = pandas.DataFrame(scaler.transform(test_dataset.drop(labels, axis=1)))
  y_test[target_label] = test_dataset[target_label]


In [ ]:
y_td['label_1']

0        45
1        45
2        45
3        45
4        45
         ..
28515    39
28516    39
28517    39
28518    39
28519    39
Name: label_1, Length: 28520, dtype: int64

In [ ]:
y_td['label_2']

480      25.0
481      25.0
482      25.0
483      25.0
484      25.0
         ... 
28515    29.0
28516    29.0
28517    29.0
28518    29.0
28519    29.0
Name: label_2, Length: 28040, dtype: float64

In [ ]:
from sklearn import svm

classifier = svm.SVC(kernel='linear')
classifier.fit(x_td[l1],y_td[l1])

SVC(kernel='linear')

In [ ]:
from sklearn import metrics

y_pred = classifier.predict(x_vd[l1])

print(metrics.confusion_matrix(y_vd[l1],y_pred))
print(metrics.accuracy_score(y_vd[l1],y_pred))
print(metrics.precision_score(y_vd[l1],y_pred,average='weighted'))
print(metrics.recall_score(y_vd[l1],y_pred,average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9906666666666667
0.9914608132608133
0.9906666666666667


In [ ]:
from sklearn.feature_selection import SelectKBest, SelectPercentile, f_classif, mutual_info_classif

selector = SelectKBest(f_classif, k=130)
x_new = selector.fit_transform(x_td[l1],y_td[l1])
print("Shape:", x_new.shape)

Shape: (28520, 130)


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_new,y_td[l1])
y_pred2 = classifier.predict(selector.transform(x_vd[l1]))
print(metrics.confusion_matrix(y_vd[l1],y_pred2))
print(metrics.accuracy_score(y_vd[l1],y_pred2))
print(metrics.precision_score(y_vd[l1],y_pred2,average='weighted'))
print(metrics.recall_score(y_vd[l1],y_pred2,average='weighted'))

[[12  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.98
0.9809063973063973
0.98


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.98, svd_solver='full')
pca.fit(x_td[l1])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l1]))
x_valid_trf = pandas.DataFrame(pca.transform(x_vd[l1]))
print(x_train_trf.shape)
print(x_valid_trf.shape)

(28520, 89)
(750, 89)


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train_trf,y_td[l1])
y_pred2 = classifier.predict(x_valid_trf)
print(metrics.confusion_matrix(y_vd[l1],y_pred2))
print(metrics.accuracy_score(y_vd[l1],y_pred2))
print(metrics.precision_score(y_vd[l1],y_pred2,average='weighted'))
print(metrics.recall_score(y_vd[l1],y_pred2,average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.988
0.9889986920486921
0.988


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_td[l3],y_td[l3])

y_pred = classifier.predict(x_vd[l3])

print(metrics.confusion_matrix(y_vd[l3],y_pred))
print(metrics.accuracy_score(y_vd[l3],y_pred))
print(metrics.precision_score(y_vd[l3],y_pred,average='weighted'))
print(metrics.recall_score(y_vd[l3],y_pred,average='weighted'))

[[142   0]
 [  1 607]]
0.9986666666666667
0.9986759906759908
0.9986666666666667


In [ ]:
selector = SelectKBest(f_classif, k=90)
x_new = selector.fit_transform(x_td[l3],y_td[l3])
print("Shape:", x_new.shape)

classifier = svm.SVC(kernel='linear')
classifier.fit(x_new,y_td[l3])
y_pred2 = classifier.predict(selector.transform(x_vd[l3]))
print(metrics.confusion_matrix(y_vd[l3],y_pred2))
print(metrics.accuracy_score(y_vd[l3],y_pred2))
print(metrics.precision_score(y_vd[l3],y_pred2,average='weighted'))
print(metrics.recall_score(y_vd[l3],y_pred2,average='weighted'))

Shape: (28520, 90)
[[142   0]
 [  0 608]]
1.0
1.0
1.0


In [ ]:
pca = PCA(n_components=0.9, svd_solver='full')
pca.fit(x_td[l3])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l3]))
x_valid_trf = pandas.DataFrame(pca.transform(x_vd[l3]))
print(x_train_trf.shape)

classifier = svm.SVC(kernel='linear')
classifier.fit(x_train_trf,y_td[l3])
y_pred2 = classifier.predict(x_valid_trf)
print(metrics.confusion_matrix(y_vd[l3],y_pred2))
print(metrics.accuracy_score(y_vd[l3],y_pred2))
print(metrics.precision_score(y_vd[l3],y_pred2,average='weighted'))
print(metrics.recall_score(y_vd[l3],y_pred2,average='weighted'))

(28520, 49)
[[142   0]
 [  0 608]]
1.0
1.0
1.0


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_td[l1],y_td[l1])

y_pred = classifier.predict(x_test[l1])
pandas.DataFrame(y_pred).to_csv("l1_before.csv")

In [ ]:
pca = PCA(n_components=0.98, svd_solver='full')
pca.fit(x_td[l1])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l1]))
x_test_trf = pandas.DataFrame(pca.transform(x_test[l1]))
print(x_train_trf.shape)
print(x_test_trf.shape)

(28520, 89)
(750, 89)


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train_trf,y_td[l1])
y_pred2 = classifier.predict(x_test_trf)
pandas.DataFrame(y_pred2).to_csv("l1_after.csv")

In [ ]:
x_test_trf.to_csv("fl1.csv")

In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_td[l3],y_td[l3])

y_pred = classifier.predict(x_test[l3])
pandas.DataFrame(y_pred).to_csv("l3_before.csv")

In [ ]:
selector = SelectPercentile(f_classif, percentile=10)
x_new = selector.fit_transform(x_td[l3],y_td[l3])
print(x_new.shape)

(28520, 26)


In [ ]:
pandas.DataFrame(x_new).to_csv("fl3")

In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_new,y_td[l3])
y_pred2 = classifier.predict(selector.transform(x_test[l3]))
pandas.DataFrame(y_pred2).to_csv("l3_after_sp.csv")

In [ ]:
pca = PCA(n_components=0.9, svd_solver='full')
pca.fit(x_td[l3])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l3]))
x_test_trf = pandas.DataFrame(pca.transform(x_test[l3]))
print(x_train_trf.shape)
print(x_test_trf.shape)

(28520, 49)
(750, 49)


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train_trf,y_td[l3])
y_pred2 = classifier.predict(x_test_trf)
pandas.DataFrame(y_pred2).to_csv("l3_after2.csv")

In [ ]:
x_test_trf.to_csv("fl3.csv")

In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_td[l2],y_td[l2])

y_pred = classifier.predict(x_test[l2])
pandas.DataFrame(y_pred).to_csv("l2_before.csv")

In [ ]:
pca = PCA(n_components=0.99, svd_solver='full')
pca.fit(x_td[l2])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l2]))
x_test_trf = pandas.DataFrame(pca.transform(x_test[l2]))
print(x_train_trf.shape)
print(x_test_trf.shape)

(28040, 106)
(750, 106)


In [ ]:
x_test_trf.to_csv("fl2_2.csv")

In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train_trf,y_td[l2])
y_pred2 = classifier.predict(x_test_trf)
pandas.DataFrame(y_pred2).to_csv("l2_after2.csv")

In [ ]:
classifier = svm.SVC(kernel='linear', class_weight='balanced')
classifier.fit(x_td[l4],y_td[l4])

y_pred = classifier.predict(x_test[l4])
pandas.DataFrame(y_pred).to_csv("l4_before.csv")

In [ ]:
pca = PCA(n_components=0.98, svd_solver='full')
pca.fit(x_td[l4])
x_train_trf = pandas.DataFrame(pca.transform(x_td[l4]))
x_test_trf = pandas.DataFrame(pca.transform(x_test[l4]))
print(x_train_trf.shape)
print(x_test_trf.shape)

(28520, 89)
(750, 89)


In [ ]:
x_test_trf.to_csv("fl4.csv")

In [ ]:
classifier = svm.SVC(kernel='linear', class_weight='balanced')
classifier.fit(x_train_trf,y_td[l4])
y_pred2 = classifier.predict(x_test_trf)
pandas.DataFrame(y_pred2).to_csv("l4_after.csv")